name: Build POI API

on:
  push:
#    paths:
#      - 'apis/poi'
    branches: [ poi-branch ]
  pull_request:
#    paths:
#      - 'apis/poi'
    branches: [ poi-branch ]
    
jobs:
  build:
    defaults:
      run:
        working-directory: ./apis/poi
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.*
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
