name: Deploy POI API (TEST ONLY)

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
    
jobs:
  
  package:   
            
    defaults:
      run:
        working-directory: ./apis/poi/web
        
    runs-on: ubuntu-latest
    steps:
      - name: Wait on Staging Slot being Healthy (200)
        uses: iFaxity/wait-on-action@v1
        with: 
          resource: https-get://openhacku454g2u9poi-staging.azurewebsites.net/api/healthcheck/poi
          
      
